version: '2'

vars:
  TODAY: {sh: date +%F-%H%M%S}

tasks:
  deploy-bootstrap:
    desc: deploy bootstrap file to S3
    cmds:
      - aws s3 cp bootstrap.sh s3://{{.S3_BUCKET}}

  deploy-cloud9:
    desc: launch new cloud9 env
    cmds:
      - aws cloudformation create-stack
          --stack-name "cloud9-ide-{{.TODAY}}"
          --capabilities CAPABILITY_IAM
          --template-url https://aws-quickstart.s3.amazonaws.com/quickstart-cloud9-ide/templates/cloud9-ide-instance.yaml
          --parameters ParameterKey=BootstrapScriptS3Uri,ParameterValue=s3://{{.S3_BUCKET}}/bootsrap.sh
            ParameterKey=C9InstanceType,ParameterValue=m5.large
            ParameterKey=C9Subnet,ParameterValue={{.SUBNET_ID}}
